server:
  port: 8089

eureka:
  client:
    serviceUrl:
#      defaultZone: http://192.168.3.39:1111/eureka/
      defaultZone:  http://127.0.0.1:1111/eureka
    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/doc.html

spring:
  application:
    name: activiti-center
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://61.164.218.155:62306/activiti-center?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: qazpl,123!
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true
  activiti:
    check-process-definitions: false
  mvc:
    view:
      prefix: classpath:/templates
      suffix: .html
  thymeleaf:
    mode: LEGACYHTML5