#端口配置
server:
  port: 7010
#admin监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
#spring 配置
spring:
  application:
    name: data-backup-center
  datasource:
    url: jdbc:mysql://localhost:3306/backup-center?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: qazpl,123!
    driver-class-name:  com.mysql.cj.jdbc.Driver
    #连接池配置(通常来说，只需要修改initialSize、minIdle、maxActive
    initial-size: 1
    max-active: 20
    min-idle: 1
    max-wait: 60000
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    validation-query: SELECT 'x'
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    filters: stat,wall
    web-stat-filter.enabled: true
    web-stat-filter.url-pattern:  /*
    web-stat-filter.exclusions: "*.js , *.gif ,*.jpg ,*.png ,*.css ,*.ico , /druid/*"
    web-stat-filter.session-stat-max-count: 1000
    web-stat-filter.profile-enable: true
    stat-view-servlet.enabled: true
    stat-view-servlet.url-pattern:  /druid/*
    stat-view-servlet.reset-enable:  true
    stat-view-servlet.login-username: admin
    stat-view-servlet.login-password: admin
  redis:
    ################### redis 单机版 start ##########################
    host: localhost
    port: 6379
    password: qazpl,123!
    timeout: 6000
    database: 3
    lettuce:
      pool:
        max-active: 10 # 连接池最大连接数（使用负值表示没有限制）,如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
        max-idle: 8   # 连接池中的最大空闲连接 ，默认值也是8
        max-wait: 100 # # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        min-idle: 2    # 连接池中的最小空闲连接 ，默认值也是0
      shutdown-timeout: 100ms

#Mybatis 配置
mybatis-plus:
  global-config:
    banner: false
  configuration:
    #打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    ##配置JdbcTypeForNull
    jdbc-type-for-null: 'null'
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

#设置最大超时时间
ribbon:
  ServerListRefreshInterval: 10  #刷新服务列表源的间隔时间
  OkToRetryOnAllOperations: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  ReadTimeout: 16000
  ConnectTimeout: 16000

#熔断降级
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 16000
#日志打印参数
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE


#eureka client配置
eureka:
  client:
    serviceUrl:
      defaultZone:  http://192.168.3.39:1111/eureka
    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5  #每隔几秒告诉eureka服务器我还存活，用于心跳检测
    lease-expiration-duration-in-seconds: 10 #如果心跳检测一直没有发送，10秒后会从eureka服务器中将此服务剔除
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/doc.html # ${server.port}为该服务的端口号

#xxl-job配置
xxl:
  job:
    admin:
      addresses: http://localhost:7008/xxl-job-admin
    accessToken: c2cfea94-2f32-4c2f-b3bf-e96fd5afa66b
    executor:
      appid: 2
      appname: xxl-job-backup-executor
      address:
      ip:
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
    handler:
      name: backupJobHandler

#mysqlbin路径
mysql:
  path: /usr/local/mysql/bin
  savePath: /data/mysql_backup/